name: CI

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Cache dist directory
        uses: actions/cache/save@v3
        with:
          path: dist
          key: ${{ runner.os }}-dist

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Restore cached dist directory
        uses: actions/cache/restore/@v3
        with:
          path: dist
          key: ${{ runner.os }}-dist

      - name: Run tests
        run: npm run test
